### ISSUE TITLE
Support IAP in kindle devices

### ISSUE THREAD

**Issue by Rockvole** [JackAppDev/flutter_iap#11]
Hi,
Do you plan to add support for Amazon Kindle devices ?

**Comment by JackAppDev** [comment]
Are they not supported because they don't use Google play?

**Comment by Rockvole** [comment]
The Apple App Store does not use Google Play.

**Comment by Rockvole** [comment]
https://developer.amazon.com/docs/in-app-purchasing/iap-migrate-from-google-iab-to-amazon-iap.html

**Comment by JackAppDev** [comment]
Its easy to know what platform the flutter app is running on (iOS/Android) but im not sure if there is an easy way for detecting amazon devices.

**Comment by Rockvole** [comment]
I believe you would detect which store is installed. So to detect the play store, you can do :

    if(AndroidTools.isPackageInstalled(context, AndroidTools.C_PLAY_STORE) {
      // Play store available
    }

    public static final String C_PLAY_STORE = "com.android.vending";
    public static final boolean isPackageInstalled(Context ctx, String packageName) {
        try {
            ctx.getPackageManager().getPackageInfo(packageName, 0);
        } catch (PackageManager.NameNotFoundException e) {
            return false;
        }
        return true;
    }

**Comment by Rockvole** [comment]
Looks like Amazon is <code>com.amazon.venezia</code>

https://stackoverflow.com/questions/17629787/how-android-app-can-detect-what-store-installed-it

**Comment by JackAppDev** [comment]
I suggest you submit a PR. I do not plan on adding this myself.

**Comment by Rockvole** [comment]
I asked amazon :
https://forums.developer.amazon.com/questions/180254/support-flutter-iap-for-kindle-devices.html

**Comment by Rockvole** [comment]
Incase anyone is looking for it, the dooboolabs plugin now supports Amazon kindle devices.
https://github.com/dooboolab/flutter_inapp_purchase
