### ISSUE TITLE
Consumable products

### ISSUE THREAD

**Issue by RobertBrunhage** [JackAppDev/flutter_iap#20]
Tested this out because I read that it supports Consumable products. It seems to say that the second time you buy a product that I already own it, so I can't buy another. I need to make the user able to buy an item multiple times (for example a potion in a game).

    response = await FlutterIap.buy('first.product.store');

That is the line I am using but for some reason. The first the I buy it. it crashes, the second time it works and crashes, the third time it says I already own this item. This is with the app in release in play store in the testing segment so I am not really getting any error messages

**Comment by JackAppDev** [comment]
I haven't had any issues buying something multiple times on either platform. Could you check that the item is listed as consumable?

**Comment by RobertBrunhage** [comment]
Sorry that I haven't answered in a while. When setting up a product in play store I can only choose it to be either a product or subscription so there is no way (that I know of) to list it as a consumable.

**Comment by JackAppDev** [comment]
Just checked, you're right. You would have to set it as a product. Try to get the crash log so I have an idea why it doesn't work for you.

**Comment by JackAppDev** [comment]
@RobertBrunhage it's set up to automatically consume purchases on Android (maybe iOS too)

**Comment by JackAppDev** [comment]
I'm planning on doing subscriptions within a week

**Comment by JackAppDev** [comment]
@ened why do you think it won't consume anything for op?

**Comment by ened** [comment]
Not sure what means "for op", but:
Currently Android buys and consumes, effectively eliminating the `Non-Consumable` IAP type.

I will probably get to this (after the iOS stuff) today.

**Comment by RobertBrunhage** [comment]
Closing this as being stale and I haven't tested this in 5 years :)
