### ISSUE TITLE
Make available token/receipt data for verification

### ISSUE THREAD

**Issue by Lastmanstanding** [JackAppDev/flutter_iap#22]
There is a need to do server side verification of the purchases. We are currently only implementing the android platform in-app purchase, but the IAPResponse returned from the 'buy' method does not contain the necessary token or receipts needed for server side verification (eg. through https://developers.google.com/android-publisher/api-ref/purchases/products/get).

**Comment by JackAppDev** [comment]
@FaisalAbid @ened would you be able to help with the android side?

**Comment by ItsCalebJones** [comment]
I'm currently on a two week vacation - willing to help with the Android side when I get back around August 1st.

**Comment by ened** [comment]
Also on vacation 🍻🍻 back on desk in 3 weeks

**Comment by JackAppDev** [comment]
Should be working now for Android with https://github.com/JackAppDev/flutter_iap/commit/9fead94f456194a797944451057e68aaadc5c86b

**Comment by Lastmanstanding** [comment]
Indeed. All's ok.
