### ISSUE TITLE
[iOS] FlutterIap.buy() always returns 'emptyProducts', doesn't prompt user for purchase.

### ISSUE THREAD

**Issue by ItsCalebJones** [JackAppDev/flutter_iap#24]
Maybe I am missing something with iOS - i'm fairly new to the platform... anyways I have a In-App-Product configured with the ID '2018_founder'. 

If I call FlutterIap.fetchProducts(["2018_founder"]) it properly grabs all the details of the product, however if I call FlutterIap.buy('2018_founder') nothing happens for the user and if i'm on the simulator I can see the method is returning a 'emptyProducts' response. This occurs both in debug and release builds from what I can tell.

All relevant code is here: https://github.com/ItsCalebJones/spacelaunchnow_flutter/blob/master/lib/views/settings/settings_page.dart

**Comment by JackAppDev** [comment]
Is this on ios, Android, or both? Also, neither platform allows testing in app purchases in the simulator.

**Comment by ItsCalebJones** [comment]
I am only using Flutter on iOS for now - this occurs both with real devices deployed to the App Store and in the simulator (apparently seeing that StoreKit might be testable now).

**Comment by ItsCalebJones** [comment]
From searching through the repo - [here ](https://github.com/JackAppDev/flutter_iap/blob/master/ios/Classes/SwiftFlutterIapPlugin.swift#L41-L44)is the only place 'emptyProducts' is returned - I don't know enough about StoreKit or Swift to understand why iapProducts is equal to 0 there.

**Comment by ItsCalebJones** [comment]
@JackAppDev do you need any additional details? Willing to help however you need.

**Comment by miyoyo** [comment]
I've been lookin in there to make it work, it seems like it's looking for
`iapProducts = [String : SKProduct]()`
Yet it's only referenced three times, none of it being as an assignation, therefore it's always empty.
