### ISSUE TITLE
Exception if I provide it with multiple productIds

### ISSUE THREAD

**Issue by lukepighetti** [JackAppDev/flutter_iap#28]
`List<String> productIds = ["nine_unlocks", "ninety_nine_unlocks"];`

<img width="779" alt="screen shot 2018-07-27 at 1 35 37 pm" src="https://user-images.githubusercontent.com/666539/43337541-3ae3b0f4-91a2-11e8-8e4b-22443faf7b57.png">

`List<String> productIds = ["nine_unlocks"]`

<img width="448" alt="screen shot 2018-07-27 at 1 37 54 pm" src="https://user-images.githubusercontent.com/666539/43337561-4781b770-91a2-11e8-9b6a-72546cd8207e.png">

**Comment by JackAppDev** [comment]
Looks like this was caused by https://github.com/JackAppDev/flutter_iap/commit/7685a12116c857981d27f6a297174876ced4a6e0

**Comment by lukepighetti** [comment]
What should I do about it?

**Comment by JackAppDev** [comment]
A small PR would be helpful. Check the logic that is used when making the json response.

**Comment by miyoyo** [comment]
I might expect it to fail however, the order of the "if" might add a comma on the beginning, awaiting on @lukepighetti 's results

**Comment by JackAppDev** [comment]
@miyoyo could you refactor it to deal with an array so that we can just set result to be something like  `elements.joined(separator: joiner)`

**Comment by miyoyo** [comment]
I'm sorry, I don't know swift, I just happened to stumble upon that error :/
